/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'fujiuray' at '17/06/06 0:01' with Gradle 2.6
 *
 * @author fujiuray, @date 17/06/06 0:01
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
